name: Dependency Updates

on:
  schedule:
    - cron: '0 2 * * 1'  # Run every Monday at 2 AM UTC
  workflow_dispatch:  # Allow manual trigger

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pip-tools safety

    - name: Update requirements.txt
      run: |
        pip-compile --upgrade requirements.in
        pip-compile --upgrade requirements-dev.in

    - name: Check for security vulnerabilities
      run: |
        safety check -r requirements.txt
        safety check -r requirements-dev.txt

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'chore: update dependencies'
        title: 'chore: update dependencies'
        body: |
          Automated dependency updates
          
          This PR updates the following:
          - Updated all dependencies to their latest versions
          - Ran security checks
          - Updated lock files
          
          Please review the changes and test thoroughly before merging.
        branch: update-dependencies
        delete-branch: true

  security-audit:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install safety bandit

    - name: Run security audit
      run: |
        safety check -r requirements.txt
        bandit -r . -x tests/

    - name: Create issue on security vulnerability
      if: failure()
      uses: actions/github-script@v6
      with:
        script: |
          github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: '🚨 Security Vulnerability Detected',
            body: 'A security vulnerability has been detected in the dependencies. Please check the security audit workflow for details.',
            labels: ['security', 'bug', 'high-priority']
          })
